### ISSUE TITLE
Switch Output

### ISSUE THREAD

**Issue by leenperjasknegt** [mkorz/IntegraPy#15]
Hi, I love your project.

I can read the zone status and partition statuses but I can't figure out how I can switch an output.
Could you give me an example so I can test it in the demo.py script?

It should start with toggle_outputs but whats next? Do I need to put the output number or the output text and in what format?
FYI I am not a programmer of some sort ;)

Thanks!

**Comment by leenperjasknegt** [comment]
Bump? :)

**Comment by mkorz** [comment]
To switch the output or number of outputs you can indeed use `toggle_outputs` function with output number(s). The call looks like this (for single output):
```
integra.toggle_outputs([21])
```
or, if  you would like to toggle the multiple outputs, you can separate them with commas as the function accepts collection of outputs:

```
integra.toggle_outputs([21, 36])
```

The easiest way to get the output identifier is to launch DloadX and check the `No` value for particular output(s).

**Comment by leenperjasknegt** [comment]
Thanks! This worked.
