### ISSUE TITLE
Dodanie komendy odczytujące ostatnie zdarzenia

### ISSUE THREAD

**Issue by simryc** [mkorz/IntegraPy#5]
Witam,
poszukuję pomocy w rozbudowaniu skryptu o możliwość odczytu wydarzeń z centrali czyli komenty 8C
Pozdrawiam

**Comment by mkorz** [comment]
Summary in English: @simryc  asked to add an example showing how the event log could be retrieved. 
I am working on this issue in a separate branch (_reading-logs_), please see commit 4a02e16918f4887fe916d9daf71dc708da24cb12 for more details. 


Witam i dziękuję za zgłoszenie issue.

Proszę zajrzeć do gałęzi: _reading-logs_ - w commicie 4a02e16918f4887fe916d9daf71dc708da24cb12 rozpocząłem dodawanie czytanie dziennika wydarzeń. Przewiduję ciąg dalszy :)

Pozdrawiam,
Marcin

**Comment by mwegrzynek** [comment]
Hi!

hold your horses for a little while 😄 . I'm rewriting the whole module to make it a bit easier to integrate in external projects (take a look here: https://github.com/mwegrzynek/IntegraPy/tree/refactoring). Event parsing is already working (I hope -- right now I'm comparing my results to GuardX output).

**Comment by mkorz** [comment]
It has been added in excellent pull request https://github.com/mkorz/IntegraPy/pull/8 from @mwegrzynek
